<?php
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../utils/AuthMiddleware.php';
require_once __DIR__ . '/../utils/Logger.php';
require_once __DIR__ . '/../../vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

class ReportController
{
  private $conn;
  private $user;

  public function __construct()
  {
    $db = new Database();
    $this->conn = $db->getConnection();

    $token = $_GET['token'] ?? null;
    if ($token) {
      $_SERVER['HTTP_AUTHORIZATION'] = 'Bearer ' . $token;
    }
    $this->user = AuthMiddleware::authenticate();
  }


  public function processRequest($method, $segments)
  {

    $format = $segments[0] ?? null;

    if ($method === 'GET' && $format === 'pdf') {
      $this->generatePDF();
    } elseif ($method === 'GET' && $format === 'excel') {
      $this->generateExcel();
    } else {
      http_response_code(404);
      echo json_encode(["message" => "Report format not found or method not supported"]);
    }
  }

  private function getFilteredData()
  {
    $startDate = $_GET['start'] ?? null;
    $endDate = $_GET['end'] ?? null;
    $category = $_GET['category'] ?? null;
    $type = $_GET['type'] ?? null;

    $query = "SELECT * FROM transactions WHERE user_id = :user_id";
    if ($startDate) $query .= " AND date >= :start";
    if ($endDate) $query .= " AND date <= :end";
    if ($category) $query .= " AND category = :category";
    if ($type) $query .= " AND type = :type";
    $query .= " ORDER BY date ASC";

    $stmt = $this->conn->prepare($query);
    $stmt->bindParam(':user_id', $this->user->id);
    if ($startDate) $stmt->bindParam(':start', $startDate);
    if ($endDate) $stmt->bindParam(':end', $endDate);
    if ($category) $stmt->bindParam(':category', $category);
    if ($type) $stmt->bindParam(':type', $type);

    $stmt->execute();
    return $stmt->fetchAll();
  }

  private function generatePDF()
  {
    $data = $this->getFilteredData();

    $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
    $pdf->SetCreator(PDF_CREATOR);
    $pdf->SetAuthor($this->user->username);
    $pdf->SetTitle('Income and Expense Report');
    $pdf->SetHeaderData('', 0, 'Income and Expense Report', 'Generated by PMS System');
    $pdf->setHeaderFont(array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
    $pdf->setFooterFont(array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
    $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
    $pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
    $pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
    $pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
    $pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
    $pdf->AddPage();

    $html = '<h2>Transactions Report</h2>';
    $html .= '<table border="1" cellpadding="4">
                    <thead>
                        <tr style="background-color:#f2f2f2;">
                            <th>Date</th>
                            <th>Type</th>
                            <th>Category</th>
                            <th>Amount</th>
                            <th>Note</th>
                        </tr>
                    </thead>
                    <tbody>';

    $totalIncome = 0;
    $totalExpense = 0;

    foreach ($data as $row) {
      $html .= '<tr>
                        <td>' . $row['date'] . '</td>
                        <td>' . ucfirst($row['type']) . '</td>
                        <td>' . $row['category'] . '</td>
                        <td>' . $row['amount'] . '</td>
                        <td>' . $row['note'] . '</td>
                      </tr>';
      if ($row['type'] == 'income') {
        $totalIncome += $row['amount'];
      } else {
        $totalExpense += $row['amount'];
      }
    }

    $html .= '</tbody></table><br/>';
    $html .= '<h3>Summary</h3>';
    $html .= '<p>Total Income: ' . number_format($totalIncome, 2) . '</p>';
    $html .= '<p>Total Expense: ' . number_format($totalExpense, 2) . '</p>';
    $html .= '<p>Net Flow: ' . number_format($totalIncome - $totalExpense, 2) . '</p>';

    $pdf->writeHTML($html, true, false, true, false, '');

    Logger::action($this->user->id, 'Reports', 'Generated PDF report', ['total_income' => $totalIncome, 'total_expense' => $totalExpense]);

    ob_clean();
    $pdf->Output('report.pdf', 'D');
    exit;
  }

  private function generateExcel()
  {
    $data = $this->getFilteredData();

    $spreadsheet = new Spreadsheet();
    $sheet = $spreadsheet->getActiveSheet();

    $sheet->setCellValue('A1', 'Date');
    $sheet->setCellValue('B1', 'Type');
    $sheet->setCellValue('C1', 'Category');
    $sheet->setCellValue('D1', 'Amount');
    $sheet->setCellValue('E1', 'Note');

    $rowNum = 2;
    $totalIncome = 0;
    $totalExpense = 0;

    foreach ($data as $row) {
      // Write data to cells safely
      $sheet->setCellValue('A' . $rowNum, $row['date']);
      $sheet->setCellValue('B' . $rowNum, ucfirst($row['type']));
      $sheet->setCellValue('C' . $rowNum, $row['category']);
      $sheet->setCellValue('D' . $rowNum, $row['amount']);
      $sheet->setCellValue('E' . $rowNum, $row['note']);

      if ($row['type'] == 'income') {
        $totalIncome += $row['amount'];
      } else {
        $totalExpense += $row['amount'];
      }

      $rowNum++;
    }

    $rowNum++;
    $sheet->setCellValue('C' . $rowNum, 'Total Income:');
    $sheet->setCellValue('D' . $rowNum, $totalIncome);
    $rowNum++;
    $sheet->setCellValue('C' . $rowNum, 'Total Expense:');
    $sheet->setCellValue('D' . $rowNum, $totalExpense);
    $rowNum++;
    $sheet->setCellValue('C' . $rowNum, 'Net Flow:');
    $sheet->setCellValue('D' . $rowNum, $totalIncome - $totalExpense);

    header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    header('Content-Disposition: attachment;filename="TransactionsReport.xlsx"');
    header('Cache-Control: max-age=0');

    Logger::action($this->user->id, 'Reports', 'Generated Excel report', ['total_income' => $totalIncome, 'total_expense' => $totalExpense]);

    ob_clean();
    $writer = new Xlsx($spreadsheet);
    $writer->save('php://output');
    exit;
  }
}
